onlineMode: true

#user: brainibot@outlook.com
#password: Forbotssake

user: wickersoft@online.de
password: bot-nao-pls-k-thx

#user: Sonat0r
#password: 911wouldbang

#user: ridingaroundonabikeenough@outlook.com
#password: veresen1

#user: SayakaMiki_
#onlineMode: false


#serverIp: 127.0.0.1
serverIp: 85.131.153.100


serverPort: 25565