/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zedly.zbot;

/**
 *
 * @author Dennis
 */
public enum EntityType {

    UNKNOWN, PLAYER, MOB, MONSTER, CREEPER, SKELETON, SPIDER, GIANT_ZOMBIE, ZOMBIE, SLIME, GHAST,
    ZOMBIE_PIGMAN, ENDERMAN, CAVE_SPIDER, SILVERFISH, BLAZE, MAGMA_CUBE, ENDERDRAGON, WITHER,
    BAT, WITCH, ENDERMITE, GUARDIAN, SHULKER, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, MOOSHROOM, SNOWMAN, OCELOT,
    IRON_GOLEM, HORSE, ZOMBIE_HORSE, SKELETON_HORSE, CHESTED_HORSE, RABBIT, VILLAGER,
    BOAT, ITEM, CLOUD, MINECART, MINECART_STORAGE,
    MINECART_POWERED, ENDER_CRYSTAL, ARROW, SNOWBALL, THROWN_EGG,
    FIREBALL, FIRE_CHARGE, ENDERPEARL, WITHER_SKULL, SHULKER_BULLET,
    FALLING_BLOCK, ITEM_FRAME, EYE_OF_ENDER, THROWN_POTION, DRAGON_EGG, EXPERIENCE_BOTTLE,
    FIREWORK, LEASH_KNOT, ARMOR_STAND, FISHING_FLOAT, SPECTRAL_ARROW, TIPPED_ARROW,
    ENDERDRAGON_FIREBALL;
    
}
