package zedly.zbot.api.entity;

/**
 * Represents a minecart containing a command block.
 */
public interface MinecartCommandBlock extends Minecart
{
	/**
	 * @return the command of the command block in this
	 * minecart.
	 */
	String getCommand();

	/**
	 * @return the last output generated by the command block in
	 * this minecart.
	 */
	String getLastOutput();
}
